# IKAIKA developer toolbox settings.

[scaffold]
workspace_root = "."
bundle_prefix = "com.ikaika"
scripts_root = "~/.ikaika/scripts"

[templates.react_native]
url = "https://github.com/JDM-Github/react_native_structure.git"

[scripts.react_native]
url = "https://github.com/JDM-Github/react_native_scripts.git"
